s=set()
# s_from_list = set([1,2,3,4])
# print(s_from_list)
# print(type(s_from_list))
s.add(1)
s.add(1)
s1 = s.union([1,4])
print(s,s1)
s2= s.intersection([1,23])
print(s,s2)
s3 = s.isdisjoint(s1)
print(s3,s)
s.remove(1)
print(s)